/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import br.com.CadastroFuncionario.Model.Carros;
import br.com.CadastroFuncionario.Model.Clientes;
import br.com.CadastroFuncionario.Model.Fornecedores;
import br.com.CadastroFuncionario.Model.Motos;
import br.com.CadastroFuncionario.Repositorio.CarrosRepositorio;
import br.com.CadastroFuncionario.Repositorio.ClienteRepositorio;
import br.com.CadastroFuncionario.Repositorio.FornecedorRepositorio;
import br.com.CadastroFuncionario.Repositorio.MotosRepositorio;
import connection.Conexão;
import java.sql.Connection;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;



/**
 *
 * @author pg1
 */
public final class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        
       DefaultTableModel modelo1 = (DefaultTableModel) tcarros.getModel();
       tcarros.setRowSorter(new TableRowSorter(modelo1));
        
        
       DefaultTableModel modelo2 = (DefaultTableModel) tcliente.getModel();
       tcliente.setRowSorter(new TableRowSorter(modelo2));
       
       DefaultTableModel modelo3 = (DefaultTableModel) tmotos.getModel();
       tmotos.setRowSorter(new TableRowSorter(modelo3));
       
       DefaultTableModel modelo4 = (DefaultTableModel) tfornecedor.getModel();
       tfornecedor.setRowSorter(new TableRowSorter(modelo4));
       
       readjtablecarros();
       readjtablecliente();
       readtablemotos();
       readtablefornecedores();
  }

    public void readtablefornecedores(){
         DefaultTableModel modelo4 = (DefaultTableModel) tfornecedor.getModel();
           modelo4.setNumRows(0);
           FornecedorRepositorio FP = new FornecedorRepositorio();
           
           FP.read().forEach((f) -> {
               modelo4.addRow(new Object[]{
                   
                   f.getID(),
                   f.getNome(),
                   f.getCNPJ(),
                   f.getTelefone()
                       
                       
                       
                       
                       
               });
        });  
           
    }
    
    public void readjtablecarros(){
     DefaultTableModel modelo1 = (DefaultTableModel) tcarros.getModel();
     modelo1.setNumRows(0);
    CarrosRepositorio FR = new CarrosRepositorio();
     
    FR.read().forEach((CC) -> {
        modelo1.addRow(new Object[]{
            CC.getId(),
            CC.getModelo(),
            CC.getAnoFabricacao(),
            CC.getPlaca(),
            CC.getCor()
                
                
                
                
    });
      });
        
  }
    
    
   public void readjtablecliente(){
         DefaultTableModel modelo2 = (DefaultTableModel) tcliente.getModel();
         modelo2.setNumRows(0); 
         ClienteRepositorio LR = new ClienteRepositorio();
          
       
        LR.read().forEach((c1) -> {
              modelo2.addRow(new Object[]{
                  
                 c1.getID(),
                 c1.getNome(),
                 c1.getCPF(),
                  c1.getTelefone()
                      
                      
                      
                      
             });
        });
         
    
   }
   
              public void readtablemotos(){
              DefaultTableModel modelo3 = (DefaultTableModel) tmotos.getModel();
                 modelo3.setNumRows(0); 
                 MotosRepositorio MR = new MotosRepositorio();
                 
                 
                 MR.read().forEach((M) -> {
                     modelo3.addRow(new Object[]{
                    
                         M.getId(),
                         M.getModelo(),
                         M.getAnoFabricacao(),
                         M.getPlaca(),
                         M.getCor()
                     });
        });
                  
                  
                  
              }
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_C = new javax.swing.JTabbedPane();
        l = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tcarros = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        lbl_anoF = new javax.swing.JLabel();
        lbl_placa = new javax.swing.JLabel();
        lbl_modelo = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        fabricacao = new javax.swing.JTextField();
        placa = new javax.swing.JTextField();
        cor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_cadastrarC = new javax.swing.JButton();
        btn_editarC = new javax.swing.JButton();
        btn_excluirC = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        bPDF = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tcliente = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cpfc = new javax.swing.JTextField();
        nomec = new javax.swing.JTextField();
        telefonec = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tmotos = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        modelom = new javax.swing.JTextField();
        anom = new javax.swing.JTextField();
        placam = new javax.swing.JTextField();
        corm = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tfornecedor = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nomef = new javax.swing.JTextField();
        cnpjf = new javax.swing.JTextField();
        telefonef = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tcarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Modelo", "Ano Fabricação", "Placa", "Cor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tcarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tcarrosMouseClicked(evt);
            }
        });
        tcarros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcarrosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tcarros);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        lbl_anoF.setText("Ano Fabricação:");

        lbl_placa.setText("Placa:");

        lbl_modelo.setText("Modelo:");

        jLabel1.setText("Cor:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbl_anoF, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbl_placa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 287, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lbl_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_modelo)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_anoF)
                    .addComponent(fabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_placa)
                    .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btn_cadastrarC.setText("Cadastrar");
        btn_cadastrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarCActionPerformed(evt);
            }
        });

        btn_editarC.setText("Atualizar");
        btn_editarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarCActionPerformed(evt);
            }
        });

        btn_excluirC.setText("Excluir");
        btn_excluirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirCActionPerformed(evt);
            }
        });

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        bPDF.setText("PDF");
        bPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lLayout = new javax.swing.GroupLayout(l);
        l.setLayout(lLayout);
        lLayout.setHorizontalGroup(
            lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
            .addGroup(lLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(lLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btn_cadastrarC)
                .addGap(96, 96, 96)
                .addComponent(btn_editarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_excluirC)
                .addGap(73, 73, 73))
            .addGroup(lLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btn_salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bPDF)
                .addGap(44, 44, 44))
        );
        lLayout.setVerticalGroup(
            lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrarC)
                    .addComponent(btn_editarC)
                    .addComponent(btn_excluirC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btn_salvar))
                    .addGroup(lLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(bPDF)))
                .addGap(52, 52, 52))
        );

        tab_C.addTab("Carros", l);

        tcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tclienteMouseClicked(evt);
            }
        });
        tcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tclienteKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tcliente);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel5.setText("Nome:");

        jLabel6.setText("CPF:");

        jLabel7.setText("Telefone:");

        cpfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomec, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(cpfc)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(telefonec, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cpfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(nomec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(telefonec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jButton6.setText("Cadastrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Atualizar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Excluir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Salvar");

        jButton10.setText("Cancelar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton6)
                .addGap(117, 117, 117)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(64, 64, 64))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(89, 89, 89))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addComponent(jButton9))
                .addGap(0, 146, Short.MAX_VALUE))
        );

        tab_C.addTab("Cliente", jPanel2);

        tmotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Modelo", "Ano Fabricação", "Placa", "Cor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tmotos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmotosMouseClicked(evt);
            }
        });
        tmotos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tmotosKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tmotos);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel4.setText("Modelo:");

        jLabel8.setText("Ano Fabricação:");

        jLabel9.setText("Placa:");

        placam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placamActionPerformed(evt);
            }
        });

        corm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modelom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anom, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(corm, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placam, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 315, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(modelom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(anom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(placam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(corm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton11.setText("Cadastrar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Atualizar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Cancelar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Salvar");

        jButton15.setText("Cancelar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton11)
                .addGap(76, 76, 76)
                .addComponent(jButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addGap(68, 68, 68))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addGap(84, 84, 84))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addGap(13, 13, 13)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton15))
                .addGap(0, 153, Short.MAX_VALUE))
        );

        tab_C.addTab("Motos", jPanel3);

        tfornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CNPJ", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tfornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfornecedorMouseClicked(evt);
            }
        });
        tfornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfornecedorKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tfornecedor);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel10.setText("Nome:");

        jLabel11.setText("CNPJ:");

        jLabel12.setText("Telefone:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(nomef, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(cnpjf))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonef)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nomef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cnpjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(telefonef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jButton16.setText("Cadastrar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("Atualizar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Excluir");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("Salvar");

        jButton20.setText("Cancelar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton16)
                .addGap(87, 87, 87)
                .addComponent(jButton17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton18)
                .addGap(85, 85, 85))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton20)
                .addGap(126, 126, 126))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton16)
                    .addComponent(jButton17)
                    .addComponent(jButton18))
                .addGap(46, 46, 46)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton19)
                    .addComponent(jButton20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_C.addTab("Fornecedor", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_C)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tab_C, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfcActionPerformed
    
       
// TODO add your handling code here:
    }//GEN-LAST:event_cpfcActionPerformed

    private void placamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placamActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
cadastrarmotos();  
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btn_cadastrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarCActionPerformed
     cadastrarcarros();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cadastrarCActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    cadastrarclientes();    
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
    
     cadastrarfornecedor();


        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void cormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cormActionPerformed

    private void tcarrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcarrosKeyReleased
       if (tcarros.getSelectedRow() != -1) {

           modelo.setText(tcarros.getValueAt(tcarros.getSelectedRow(), 1).toString());
            fabricacao.setText(tcarros.getValueAt(tcarros.getSelectedRow(), 2).toString());
            placa.setText(tcarros.getValueAt(tcarros.getSelectedRow(), 3).toString());
             cor.setText(tcarros.getValueAt(tcarros.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_tcarrosKeyReleased

    private void tcarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tcarrosMouseClicked
       if (tcarros.getSelectedRow() != -1) {

           modelo.setText(tcarros.getValueAt(tcarros.getSelectedRow(), 1).toString());
            fabricacao.setText(tcarros.getValueAt(tcarros.getSelectedRow(), 2).toString());
            placa.setText(tcarros.getValueAt(tcarros.getSelectedRow(), 3).toString());
             cor.setText(tcarros.getValueAt(tcarros.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_tcarrosMouseClicked

    private void tclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tclienteKeyReleased
        if (tcliente.getSelectedRow() != -1) {

           nomec.setText(tcliente.getValueAt(tcliente.getSelectedRow(), 1).toString());
            cpfc.setText(tcliente.getValueAt(tcliente.getSelectedRow(), 2).toString());
            telefonec.setText(tcliente.getValueAt(tcliente.getSelectedRow(), 3).toString());

        }
    }//GEN-LAST:event_tclienteKeyReleased

    private void tclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tclienteMouseClicked
        if (tcliente.getSelectedRow() != -1) {

           nomec.setText(tcliente.getValueAt(tcliente.getSelectedRow(), 1).toString());
            cpfc.setText(tcliente.getValueAt(tcliente.getSelectedRow(), 2).toString());
            telefonec.setText(tcliente.getValueAt(tcliente.getSelectedRow(), 3).toString());

        }
    }//GEN-LAST:event_tclienteMouseClicked

    private void tmotosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tmotosKeyReleased
       if (tmotos.getSelectedRow() != -1) {

            modelom.setText(tmotos.getValueAt(tmotos.getSelectedRow(), 1).toString());
            anom.setText(tmotos.getValueAt(tmotos.getSelectedRow(), 2).toString());
            placam.setText(tmotos.getValueAt(tmotos.getSelectedRow(), 3).toString());
             corm.setText(tmotos.getValueAt(tmotos.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_tmotosKeyReleased

    private void tmotosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmotosMouseClicked
if (tmotos.getSelectedRow() != -1) {

            modelom.setText(tmotos.getValueAt(tmotos.getSelectedRow(), 1).toString());
            anom.setText(tmotos.getValueAt(tmotos.getSelectedRow(), 2).toString());
            placam.setText(tmotos.getValueAt(tmotos.getSelectedRow(), 3).toString());
             corm.setText(tmotos.getValueAt(tmotos.getSelectedRow(), 4).toString());
        }     
    }//GEN-LAST:event_tmotosMouseClicked

    private void tfornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfornecedorKeyReleased
   if (tfornecedor.getSelectedRow() != -1) {

            nomef.setText(tfornecedor.getValueAt(tfornecedor.getSelectedRow(), 1).toString());
            cnpjf.setText(tfornecedor.getValueAt(tfornecedor.getSelectedRow(), 2).toString());
            telefonef.setText(tfornecedor.getValueAt(tfornecedor.getSelectedRow(), 3).toString());
             
        }     
    }//GEN-LAST:event_tfornecedorKeyReleased

    private void tfornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfornecedorMouseClicked
     
        if (tfornecedor.getSelectedRow() != -1) {

            nomef.setText(tfornecedor.getValueAt(tfornecedor.getSelectedRow(), 1).toString());
            cnpjf.setText(tfornecedor.getValueAt(tfornecedor.getSelectedRow(), 2).toString());
            telefonef.setText(tfornecedor.getValueAt(tfornecedor.getSelectedRow(), 3).toString());



        }

    }//GEN-LAST:event_tfornecedorMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
   
    atualizarcliente();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btn_editarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarCActionPerformed
     atualizarcarros();     
        
        
    }//GEN-LAST:event_btn_editarCActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
atualizarmotos();      
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
   atualizarfornecedor();      
    }//GEN-LAST:event_jButton17ActionPerformed

    private void btn_excluirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirCActionPerformed
    excluircarros();      

    }//GEN-LAST:event_btn_excluirCActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
excluirclientes();     
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
  excluirmotos();      
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
  excluirfornecedor(); 
                                       

        
        
    }//GEN-LAST:event_jButton18ActionPerformed

    private void bPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPDFActionPerformed
        
         Connection con = Conexão.getConnection();   
    String src = "carros.jasper";
        
        JasperPrint jaspertPrint = null;
        
        try {
            
            jaspertPrint = JasperFillManager.fillReport(src, null, con);
            
        } catch (JRException ex) {
            System.out.println("Error: "+ex);
        }
        
        JasperViewer view = new JasperViewer(jaspertPrint,false);
        
        view.setVisible(true);
        
    }//GEN-LAST:event_bPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anom;
    private javax.swing.JButton bPDF;
    private javax.swing.JButton btn_cadastrarC;
    private javax.swing.JButton btn_editarC;
    private javax.swing.JButton btn_excluirC;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JTextField cnpjf;
    private javax.swing.JTextField cor;
    private javax.swing.JTextField corm;
    private javax.swing.JTextField cpfc;
    private javax.swing.JTextField fabricacao;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel l;
    private javax.swing.JLabel lbl_anoF;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_placa;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField modelom;
    private javax.swing.JTextField nomec;
    private javax.swing.JTextField nomef;
    private javax.swing.JTextField placa;
    private javax.swing.JTextField placam;
    private javax.swing.JTabbedPane tab_C;
    private javax.swing.JTable tcarros;
    private javax.swing.JTable tcliente;
    private javax.swing.JTextField telefonec;
    private javax.swing.JTextField telefonef;
    private javax.swing.JTable tfornecedor;
    private javax.swing.JTable tmotos;
    // End of variables declaration//GEN-END:variables

    
public void carrospdf(){
    
  
            
      
   


}

      public void cadastrarcarros(){
          
       CarrosRepositorio CR = new CarrosRepositorio();
       Carros i = new Carros ();
       
       
       i.setModelo(modelo.getText());
       i.setAnoFabricacao(Integer.parseInt(fabricacao.getText()));
       i.setPlaca(placa.getText());
       i.setCor(cor.getText()); 
       
       
       CR.create(i);
       
       modelo.setText("");
       fabricacao.setText("");
       placa.setText("");
       cor.setText("");
        readjtablecarros();
        
      }

  public void atualizarcarros(){
       
         if (tcarros.getSelectedRow() != -1) {

            Carros C = new Carros();
            CarrosRepositorio CA = new CarrosRepositorio();

        C.setModelo(modelo.getText());
       C.setCor(cor.getText());
       C.setAnoFabricacao(Integer.parseInt(fabricacao.getText()));
       C.setPlaca(placa.getText());
       C.setId((int)(tcarros.getValueAt(tcarros.getSelectedRow(), 0)));
        CA.update(C);

        modelo.setText("");
        cor.setText("");
        fabricacao.setText("");
        placa.setText("");

        readjtablecarros();

        }
  }
   public void excluircarros(){
         if (tcarros.getSelectedRow() != -1) {

            Carros C = new Carros();
            CarrosRepositorio CR = new CarrosRepositorio();

       
       C.setId((int)(tcarros.getValueAt(tcarros.getSelectedRow(), 0)));
        CR.delete(C);

        modelo.setText("");
        fabricacao.setText("");
        placa.setText("");

        readjtablecarros();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
   }
        public void cadastrarclientes(){
            
            
                
        ClienteRepositorio CLR = new ClienteRepositorio();
        Clientes CL = new Clientes();
        
        CL.setNome(nomec.getText());
        CL.setCPF(Integer.parseInt(cpfc.getText()));
        CL.setTelefone(Integer.parseInt(telefonec.getText()));
        
        nomec.setText("");
        cpfc.setText("");
        telefonec.setText("");
        
       CLR.creatcliente(CL);
        readjtablecliente();
        
    }
 
public void atualizarcliente(){
    if (tcliente.getSelectedRow() != -1) {

            Clientes C2 = new Clientes();
            ClienteRepositorio CR = new ClienteRepositorio();

        C2.setNome(nomec.getText());
      C2.setCPF(Integer.parseInt(cpfc.getText()));
       C2.setTelefone(Integer.parseInt(telefonec.getText()));
       C2.setID((int)(tcliente.getValueAt(tcliente.getSelectedRow(), 0)));
        CR.update(C2);

        nomec.setText("");
        cpfc.setText("");
        telefonec.setText("");

        readjtablecliente();

        }

}
  public void excluirclientes(){
      
      
       if (tcliente.getSelectedRow() != -1) {

            Clientes CL = new Clientes();
            ClienteRepositorio CLR = new ClienteRepositorio();

       
       CL.setID((int)(tcliente.getValueAt(tcliente.getSelectedRow(), 0)));
        CLR.delete(CL);

        nomec.setText("");
        cpfc.setText("");
        telefonec.setText("");

        readjtablecliente();
        } 

      
  }


public void cadastrarmotos(){
    
     MotosRepositorio MR = new MotosRepositorio();
   Motos M = new Motos();
   
   M.setModelo(modelom.getText());
   M.setAnoFabricacao(Integer.parseInt(anom.getText()));
   M.setPlaca(placam.getText());
   M.setCor(corm.getText());
   
   MR.createmotos(M);
   
   modelom.setText("");
   anom.setText("");
   placam.setText("");
   corm.setText("");
      readtablemotos();  
    
    
    
}

         public void atualizarmotos(){
        
         if (tmotos.getSelectedRow() != -1) {

            Motos M = new Motos();
            MotosRepositorio M1 = new MotosRepositorio();

       M.setModelo(modelom.getText());
       M.setCor(corm.getText());
       M.setAnoFabricacao(Integer.parseInt(anom.getText()));
       M.setPlaca(placam.getText());
       M.setId((int)(tmotos.getValueAt(tmotos.getSelectedRow(), 0)));
       M1.update(M);

        modelom.setText("");
        corm.setText("");
        anom.setText("");
        placam.setText("");

       readtablemotos();

        }
}

public void excluirmotos(){
      if (tmotos.getSelectedRow() != -1) {

            Motos M = new Motos();
            MotosRepositorio MR = new MotosRepositorio();

       
       M.setId((int)(tmotos.getValueAt(tmotos.getSelectedRow(), 0)));
        MR.delete(M);

        modelom.setText("");
        anom.setText("");
        placam.setText("");

        readtablemotos();
        } }




public void cadastrarfornecedor(){
      
       FornecedorRepositorio FR = new FornecedorRepositorio();
       Fornecedores f = new Fornecedores ();

       f.setNome(nomef.getText());
       f.setTelefone(Integer.parseInt(telefonef.getText()));
       f.setCNPJ(Integer.parseInt(cnpjf.getText()));
       
       nomef.setText("");
       telefonef.setText("");
       cnpjf.setText("");

      FR.createfornecedor(f);
      readtablefornecedores();


}
  public void atualizarfornecedor(){
      if (tfornecedor.getSelectedRow() != -1) {

            Fornecedores f = new Fornecedores();
            FornecedorRepositorio f1 = new FornecedorRepositorio();

        f.setNome(nomef.getText());
        f.setCNPJ(Integer.parseInt(cnpjf.getText()));
        f.setTelefone(Integer.parseInt(telefonef.getText()));
        f.setID((int)(tfornecedor.getValueAt(tfornecedor.getSelectedRow(), 0)));
        f1.update(f);

        nomef.setText("");
        cnpjf.setText("");
        telefonef.setText("");

       readtablefornecedores();
       
        }
      
  }

  public void excluirfornecedor(){
      if (tfornecedor.getSelectedRow() != -1) {

            Fornecedores F = new Fornecedores();
            FornecedorRepositorio FR = new FornecedorRepositorio();

       
       F.setID((int)(tfornecedor.getValueAt(tfornecedor.getSelectedRow(), 0)));
        FR.delete(F);

        nomef.setText("");
        cnpjf.setText("");
        telefonef.setText("");

        readtablefornecedores();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
  }

} 






